<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Datalagring.Application\Datalagring.Application.csproj" />
    <ProjectReference Include="..\Datalagring.Infrastructure\Datalagring.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Endpoints/" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
